# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 591, 401))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("Duck.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.duck = QtWidgets.QPushButton(self.centralwidget)
        self.duck.setGeometry(QtCore.QRect(0, 450, 291, 61))
        self.duck.setObjectName("duck")
        self.alien = QtWidgets.QPushButton(self.centralwidget)
        self.alien.setGeometry(QtCore.QRect(300, 450, 291, 61))
        self.alien.setObjectName("alien")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.duck.clicked.connect(self.show_duck)
        self.alien.clicked.connect(self.show_alien)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.duck.setText(_translate("MainWindow", "Duck"))
        self.alien.setText(_translate("MainWindow", "Alien"))

    def show_duck(self):
        self.photo.setPixmap(QtGui.QPixmap("img/Duck.jpg"))
        
    def show_alien(self):
        self.photo.setPixmap(QtGui.QPixmap("img/Alien.jpg"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
